apiVersion: apps/v1
kind: Deployment
metadata:
  name: appclient
  labels:
    app: appclient
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appclient
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: appclient
    spec:
      containers:
      - image: 774209043150.dkr.ecr.ap-northeast-1.amazonaws.com/enclaveclientk8s:latest
        imagePullPolicy: Always
        name: appclient
        ports:
        - containerPort: 5000
          protocol: TCP