apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclaveserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enclaveserver
  template:
    metadata:
      labels:
        app: enclaveserver
    spec:
      containers:
      - name: enclaveserver
        image: 774209043150.dkr.ecr.ap-northeast-1.amazonaws.com/enclaveserverk8s:latest
        command: ["/home/run.sh"]
        imagePullPolicy: Always
        resources:
          limits:
            aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-2Mi: 7000Mi
            cpu: 4000m
          requests:
            aws.ec2.nitro/nitro_enclaves: "1"
        volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
          readOnly: false
          # Enable if 1Gi pages are required
          #- mountPath: /hugepages-1Gi
          #  name: hugepage-1gi
          #  readOnly: false
      volumes:
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists