####################################################################################################
## Builder
####################################################################################################
FROM rust:latest AS builder

ARG TARGETPLATFORM
# x86_64-unknown-linux-musl 
# aarch64-unknown-linux-musl

RUN rustup target add $TARGETPLATFORM
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

# Create appuser
ENV USER=myip
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"


WORKDIR /myip

COPY ./ .

RUN cargo build --target $TARGETPLATFORM --release

####################################################################################################
## Final image
####################################################################################################
FROM alpine
FROM amazonlinux:2
ARG TARGETPLATFORM

# Import from builder.
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /myip

# Copy our build
COPY --from=builder /myip/target/${TARGETPLATFORM}/release/enclave-server ./
# Copy kmstool_enclave_cli
COPY --from=builder /myip/kmstool_enclave_cli /myip/kmstool_enclave_cli
COPY --from=builder /myip/libnsm.so /myip/libnsm.so
COPY --from=builder /myip/libnsm.so /usr/lib64/libnsm.so

RUN chmod +x /myip/kmstool_enclave_cli
# RUN ls -l /myip/

ENV REGION ap-east-1
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64

# Use an unprivileged user.

CMD ["./myip/enclave-server", "-p", "7878"]
