apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: walletCluster
  region: ap-northeast-1
  version: "1.23"

managedNodeGroups:
  - name: enclave-node
    launchTemplate:
      id: lt-010dcbd15c9170314
      version: "3"
    desiredCapacity: 1
